### ISSUE TITLE
Objective C Support

### ISSUE THREAD

**Issue by scottybe** [NSHipster/ConfettiView#5]
Great framework, @mattt !

I maintain an Objective C project and tried to use the framework. I imported it successfully and can create an ConfettiView object, but it doesn't have an emit method. Is it possible to use this from Objective C?

Thanks!

**Comment by mattt** [comment]
@scottybe Thanks for the kind words. The reason why the `emit` method is inaccessible is that the `[Content]` argument can't be constructed in Objective-C. `Content` is an enumeration that has cases with associated values, which can't be imported into Objective-C directly. Support for Objective-C could be added by exposing this interface in a different way, but it's not something I plan to work on.
