### ISSUE TITLE
Missing functionality

### ISSUE THREAD

**Issue by Alarson93** [NSHipster/ConfettiView#7]
The behavior shown in the README doesn't appear possible in the current implementation. Most of the ability to customize has been closed off.

e.g. I cannot customize layers because because neither `ConfettiLayer` nor v`ar confettiLayers` are public/open. Was this intentionally removed or is this library simply incomplete?

In any case - is this library still "alive" enough that a PR adding the functionality would be approved?

**Comment by mattt** [comment]
> The behavior shown in the README doesn't appear possible in the current implementation.

What behavior specifically?

> Most of the ability to customize has been closed off. e.g. I cannot customize layers because because neither ConfettiLayer nor var confettiLayers are public/open.

The API was intentionally designed to support certain kinds of configuration, but not everything. What functionality are you looking for that isn't currently supported?

**Comment by Alarson93** [comment]
Oh! My apologies. I was installing `ConfettiView` which appears to be another pod entirely. I double checked the README and noticed that this pod is actually `ConfettiView-NSHipster`.

So, in short, I installed the wrong pod.
